config/routes.rb
ActionController::Routing::Routes.draw do |map|
	map.resources :carousels, :except => [:index, :show], :path_prefix => 'projects/:project_id', :name_prefix => 'project_'
end

app/models/carousel.rb
class Carousel < ActiveRecord::Base
  unloadable

  serialize :auto_assign, Hash

  belongs_to :project
  has_and_belongs_to_many :members, :include => [:user, :roles], 
    :conditions => "#{User.table_name}.type='User' AND #{User.table_name}.status=#{User::STATUS_ACTIVE}", :order => "#{Member.table_name}.id"
  has_many :carousel_issues, :dependent => :destroy
  has_many :issues, :through => :carousel_issues
  
  validates_presence_of :name, :project, :begin_at
  validates_numericality_of :period, :greater_or_equal_to => TimePeriod.all.min_by(&:seconds).seconds
  validate :validate_issue_settings
  
  before_save :set_issue_settings
  before_validation :set_period
  
  named_scope :to_run, :conditions => "NOW() > COALESCE(begin_at, '1970-01-01') AND NOW() > ADDDATE(COALESCE(last_run, '1970-01-01'), INTERVAL period SECOND)"
  named_scope :active, :conditions => {:active => true}
  
  def after_initialize
    self.auto_assign ||= Hash.new
  end
  
  def next_run
    self.last_run + self.period
  end
  
  def users_queue
    members.all(:include => :user).map(&:user)
  end
  
  def time_period_seconds=(time_period_seconds)
    @time_period_seconds = time_period_seconds.to_i
  end
  
  def time_period_seconds
    @time_period_seconds ||= TimePeriod.seconds(self.period.to_i)
  end
  
  def time_period_quantity=(time_period_quantity)
    @time_period_quantity = time_period_quantity.to_i
  end
  
  def time_period_quantity
    @time_period_quantity ||= TimePeriod.quantity(self.period.to_i)
  end
  
  def run
    transaction do
      issue = project.issues.create!(
        :assigned_to  =>  next_run_user,
        :author       =>  project.members.find(issue_settings.author_id).user,
        :subject      =>  issue_settings.subject,
        :category     =>  project.issue_categories.find(issue_settings.category_id),
        :tracker      =>  project.trackers.find(issue_settings.tracker_id),
        :priority     =>  IssuePriority.find(issue_settings.priority_id),
        :description  =>  issue_settings.description
      )
      carousel_issues.create!(:issue => issue, :user => issue.assigned_to)
      self.last_run = Time.now
      save!
    end
  end
  
  def issue_settings
    @issue_settings ||= CarouselIssueSettings.new(auto_assign)
  end
  alias_method :carousel_issue_settings, :issue_settings
  
  def issue_settings=(attrs)
    @issue_settings = CarouselIssueSettings.new(attrs)
  end
  alias_method :carousel_issue_settings=, :issue_settings=
  
  def next_run_user
    return nil if users_queue.empty?
    
    last_user_number = users_queue.find_index(last_run_user)
    if last_user_number
      users_queue[(last_user_number + 1) % users_queue.count]
    else
      users_queue[0]
    end
  end
  
  def last_run_user
    return nil if carousel_issues.empty?
    carousel_issues.last.user
  end
  
  private
  
  def set_issue_settings
    self.auto_assign = issue_settings.attributes
  end
  
  def set_period
    self.period = time_period_quantity * time_period_seconds
  end
  
  def validate_issue_settings
    return if issue_settings.valid?
    
    issue_settings.errors.each_full{ |msg| errors.add_to_base(msg) }
  end

end

app/models/carousel_issue.rb
class CarouselIssue < ActiveRecord::Base
  unloadable
  
  belongs_to :issue
  belongs_to :carousel
  belongs_to :user
end

app/controllers/carousels_controller.rb
class CarouselsController < ApplicationController
  unloadable
  
  menu_item :settings

  before_filter :find_project, :authorize
  before_filter :find_collections, :only => [:new, :create, :edit, :update]
  before_filter :find_carousel, :only => [:edit, :update, :destroy]

  def new
    @carousel = @project.carousels.build
  end
  
  def create
    @carousel = @project.carousels.create(params[:carousel])
    if @carousel.save
      flash[:notice] = l(:notice_successful_create)
      redirect_back
    else
      render :action => 'new'
    end
  end

  def edit; end
  
  def update
    @carousel.attributes = params[:carousel]
    
    if @carousel.save
      flash[:notice] = l(:notice_successful_update)
      redirect_back
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @carousel.destroy
    flash[:notice] = l(:notice_successful_delete)
    redirect_back
  end
  
  private
  
  def find_project
    # @project variable must be set before calling the authorize filter
    @project = Project.find(params[:project_id])
  end
  
  def find_carousel
    @carousel = @project.carousels.find(params[:id])
  end
  
  def find_collections
    @members = @project.members.all(:include => :user)
    @issue_priorities = IssuePriority.all
    @issue_categories = @project.issue_categories
    @trackers = @project.trackers
  end
  
  def redirect_back
    redirect_to :controller => 'projects', :action => 'settings', :tab => 'carousels', :id => @project
  end
end

app/helpers/carousels_helper.rb
module CarouselsHelper
	def	calendar_with_time_for(field_id)
    include_calendar_headers_tags
		image_tag("calendar.png", {:id => "#{field_id}_trigger",:class => "calendar-trigger"}) +
		javascript_tag("Calendar.setup({inputField : '#{field_id}', timeFormat : '24', showsTime : true, ifFormat : '%Y-%m-%d %H:%M', button : '#{field_id}_trigger' });")
	end
end

app/views/carousels/_header.html.erb
<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'carousels', :plugin => 'redmine_carousel' %>
<% end %>

app/views/carousels/_index.html.erb
<% if @project.carousels.empty? %>
	<p class="nodata"><%= l(:label_no_data) %></p>
<% else %>
	<table class="list carousels">
	  <thead><tr>
	    <th><%= l(:field_name) %></th>
	    <th><%= l(:field_period) %></th>
		<th><%= l(:field_members) %></th>
	    <th><%= l(:field_last_run) %></th>
	    <th><%= l(:field_active) %></th>
	    <th></th>
	  </tr></thead>
	  <tbody>
	  <% @project.carousels.each do |carousel| %>		
	  <tr class="carousel <%= cycle("odd", "even") %>">
	    <td class="carousel_name"><%= link_to carousel.name, edit_project_carousel_path(@project, carousel) %></td>
	    <td class="period"><%= distance_of_time_in_words(0, carousel.period) %></td>
		<td class="members"><%= carousel.members.map(&:name).join('<br/>') %></td>
	    <td class="last_run"><%= format_time(carousel.last_run) %></td>
		<td class="active"><%= carousel.active? ? l(:general_text_yes) : l(:general_text_no) %></td>
	    <td class="buttons">
	    <%= link_to(l(:button_edit), edit_project_carousel_path(@project, carousel), :class => 'icon icon-edit') %>
	    <%= link_to(l(:button_delete), project_carousel_path(@project, carousel), :confirm => l(:text_are_you_sure), :method => :delete, :class => 'icon icon-del') %>
	    </td>
	  </tr>		
	  <% end %>
	  </tbody>
	</table>
<% end %>

<p>
	<%= link_to l(:label_new_carousel), new_project_carousel_path(@project) %>
</p>

<% render :partial => 'carousels/header' %>

app/views/carousels/_tabular_form.html.erb
<%= error_messages_for :carousel %>
<div class="box tabular">
	<p>
		<%= tabular_form.text_field :name, :required => true %>
	</p>
	
	<p>
		<%= tabular_form.check_box :active %>
	</p>

	<p>
		<%= tabular_form.text_field :begin_at, :size => 17, :required => true %><%= calendar_with_time_for('carousel_begin_at') %></a>
	<p>
		<%= tabular_form.text_field :time_period_quantity, :required => true, :size => 2, :label => :field_period %>
		<%= tabular_form.select :time_period_seconds, options_from_collection_for_select(TimePeriod.all, :seconds, :name, @carousel.time_period_seconds), :no_label => true %>
	</p>
	
	<p>
		<%= tabular_form.select :member_ids, options_from_collection_for_select(@members, :id, :name, @carousel.member_ids), {:label => :field_members}, {:multiple => 'multiple'} %>
	</p>
</div>

<fieldset class="box tabular">
	<legend><%= l(:label_issue_settings) %></legend>
	
	<% tabular_form.fields_for @carousel.issue_settings do |issue_settings| %>

		<p>
			<%= issue_settings.text_field :subject, :required => true %>
		</p>

		<p>
			<%= issue_settings.select :tracker_id, options_from_collection_for_select(@trackers, :id, :name, @carousel.issue_settings.tracker_id), {:label => :field_tracker, :required => true} %>
		</p>
		
		<p>
			<%= issue_settings.select :priority_id, options_from_collection_for_select(@issue_priorities, :id, :name, @carousel.issue_settings.priority_id), {:label => :field_issue_priority, :required => true, :label => :field_priority} %>
		</p>
	
		<p>
			<%= issue_settings.select :category_id, options_from_collection_for_select(@issue_categories, :id, :name, @carousel.issue_settings.category_id), {:label => :field_issue_category, :required => true, :label => :field_category} %>
		</p>
	
		<p>
			<%= issue_settings.select :author_id, options_from_collection_for_select(@members, :id, :name, @carousel.issue_settings.author_id), {:label => :field_author, :required => true} %>
		</p>
	
		<p><%= issue_settings.text_area :description,
		                   :cols => 60,
		                   :rows => (@carousel.issue_settings.description.blank? ? 10 : [[10, @carousel.issue_settings.description.length / 50].max, 100].min),
		                   :accesskey => accesskey(:edit),
		                   :class => 'wiki-edit' %></p>
	
	<% end %>

</fieldset>

<%= wikitoolbar_for 'carousel_carousel_issue_settings_description' %>

app/views/carousels/edit.html.erb
<h2><%= l(:label_edit_carousel) %></h2>

<% labelled_tabular_form_for :carousel, @carousel, :url => project_carousel_url(@project, @carousel), :html => {:id => 'carousel_form', :method => 'put'} do |f| %>

	<%= render :partial => 'tabular_form', :object => f %>
	<%= f.submit 'Update' %>

<% end %>

<% render :partial => 'header' %>

app/views/carousels/index.html.erb
<% html_title l(:label_carousels) -%>

<div class="contextual">
	<%= link_to_if_authorized l(:label_new_carousel), new_project_carousel_path(@project), :class => 'icon icon-add' %>
</div>

<h2><%=l(:label_carousels)%></h2>

<% delete_allowed = User.current.allowed_to?(:destroy_carousels, @project) %>
<% edit_allowed = User.current.allowed_to?(:edit_carousels, @project) %>

<% if @carousels.empty? %>
	<p class="nodata"><%= l(:label_no_data) %></p>
<% else %>
	<table class="list carousels">
	  <thead><tr>
	    <%= sort_header_tag('name', :caption => l(:field_name)) %>
	    <%= sort_header_tag('period', :caption => l(:field_period), :default_order => 'desc') %>
		<th><%= l(:field_members) %></th>
	    <%= sort_header_tag('last_run', :caption => l(:field_last_run), :default_order => 'desc') %>
	    <th></th>
	  </tr></thead>
	  <tbody>
	  <% @carousels.each do |carousel| %>		
	  <tr class="carousel <%= cycle("odd", "even") %>">
	    <td class="carousel_name"><%= carousel.name %></td>
	    <td class="period"><%= carousel.period_name %></td>
		<td class="members"><%= carousel.members.map(&:name).join('<br/>') %></td>
	    <td class="last_run"><%= format_time(carousel.last_run) %></td>
	    <td align="center">
	    <%= link_to(image_tag('edit.png'), edit_project_carousel_path(@project, carousel)) if edit_allowed %>
	    <%= link_to(image_tag('delete.png'), project_carousel_path(@project, carousel), :confirm => l(:text_are_you_sure), :method => :delete) if delete_allowed %>
	    </td>
	  </tr>		
	  <% end %>
	  </tbody>
	</table>
<% end %>

<% render :partial => 'header' %>

app/views/carousels/new.html.erb
<h2><%= l(:label_new_carousel) %></h2>

<% labelled_tabular_form_for :carousel, @carousel, :url => project_carousels_url(@project), :html => {:id => 'carousel_form'} do |f| %>

	<%= render :partial => 'tabular_form', :object => f %>
	<%= f.submit 'Create' %>


<% end %>

<% render :partial => 'header' %>